jobs:
  fedora-25/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f25
          name: freeipa/ci-master-f25
          version: 0.2.11
        timeout: 1800

  fedora-25/installation-install-with-ca2:
    requires: [fedora-25/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-25/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA2
        template: *ci-master-f25
        timeout: 11000

